# ===== FIRST STAGE ======
ARG DDC_SMART_CONTRACT_VERSION=2.2.3
ARG ECR_REGISTRY
FROM phusion/baseimage:0.11 as builder
LABEL maintainer="team@cere.network"
LABEL description="This is the build stage to create the binary."
WORKDIR /cerenetwork
COPY . /cerenetwork

# ===== SECOND STAGE ======
FROM $ECR_REGISTRY/ddc-smart-contract:$DDC_SMART_CONTRACT_VERSION as ddc-smart-contract

FROM builder

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y cmake pkg-config libssl-dev git clang
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
	export PATH=$PATH:$HOME/.cargo/bin && \
	scripts/init.sh && \
	TRYBUILD=overwrite cargo +nightly-2021-02-11 test --workspace --locked --release --verbose --features runtime-benchmarks --manifest-path bin/node/cli/Cargo.toml && \
	SUBSTRATE_TEST_TIMEOUT=1 cargo +nightly-2021-02-11 test -p substrate-test-utils --release --verbose --locked -- --ignored timeout sccache -s
