[package]
name = "sp-consensus-slots"
<<<<<<< HEAD
version = "0.8.1"
=======
version = "0.9.0"
>>>>>>> 49a4103f4bfef55be20a5c6d26e18ff3003c3353
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for slots-based consensus"
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../runtime" }
sp-arithmetic = { version = "3.0.0", default-features = false, path = "../../arithmetic" }

[features]
default = ["std"]
std = [
	"codec/std",
	"sp-runtime/std",
	"sp-arithmetic/std",
]
