[package]
name = "sp-consensus-aura"
<<<<<<< HEAD
version = "0.8.1"
=======
version = "0.9.0"
>>>>>>> 49a4103f4bfef55be20a5c6d26e18ff3003c3353
authors = ["Parity Technologies <admin@parity.io>"]
description = "Primitives for Aura consensus"
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-application-crypto = { version = "3.0.0", default-features = false, path = "../../application-crypto" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false, path = "../../std" }
sp-api = { version = "3.0.0", default-features = false, path = "../../api" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../runtime" }
sp-inherents = { version = "3.0.0", default-features = false, path = "../../inherents" }
sp-timestamp = { version = "3.0.0", default-features = false, path = "../../timestamp" }
sp-consensus-slots = { version = "0.9.0", default-features = false, path = "../slots" }

[features]
default = ["std"]
std = [
	"sp-application-crypto/std",
	"codec/std",
	"sp-std/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-inherents/std",
	"sp-timestamp/std",
]
