[package]
name = "sc-consensus-uncles"
<<<<<<< HEAD
version = "0.8.1"
=======
version = "0.9.0"
>>>>>>> 49a4103f4bfef55be20a5c6d26e18ff3003c3353
authors = ["Parity Technologies <admin@parity.io>"]
description = "Generic uncle inclusion utilities for consensus"
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sc-client-api = { version = "3.0.0", path = "../../api" }
sp-core = { version = "3.0.0", path = "../../../primitives/core" }
sp-runtime = { version = "3.0.0", path = "../../../primitives/runtime" }
sp-authorship = { version = "3.0.0", path = "../../../primitives/authorship" }
sp-consensus = { version = "0.9.0", path = "../../../primitives/consensus/common" }
sp-inherents = { version = "3.0.0", path = "../../../primitives/inherents" }
log = "0.4.8"
