[package]
name = "pallet-transaction-payment-rpc-runtime-api"
<<<<<<< HEAD
version = "2.0.1"
=======
version = "3.0.0"
>>>>>>> 49a4103f4bfef55be20a5c6d26e18ff3003c3353
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "RPC runtime API for transaction payment FRAME pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { version = "3.0.0", default-features = false, path = "../../../../primitives/api" }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../../../primitives/runtime" }
pallet-transaction-payment = { version = "3.0.0", default-features = false, path = "../../../transaction-payment" }

[features]
default = ["std"]
std = [
	"sp-api/std",
	"codec/std",
	"sp-runtime/std",
	"pallet-transaction-payment/std",
]
