[package]
name = "frame-support-procedural"
<<<<<<< HEAD
version = "2.0.1"
=======
version = "3.0.0"
>>>>>>> 49a4103f4bfef55be20a5c6d26e18ff3003c3353
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Proc macro of Support code for the runtime."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
proc-macro = true

[dependencies]
frame-support-procedural-tools = { version = "3.0.0", path = "./tools" }
proc-macro2 = "1.0.6"
quote = "1.0.3"
<<<<<<< HEAD
syn = { version = "1.0.58", features = ["full"] }
=======
Inflector = "0.11.4"
syn = { version = "1.0.58", features = ["full"] }

[features]
default = ["std"]
std = []
>>>>>>> 49a4103f4bfef55be20a5c6d26e18ff3003c3353
