[package]
name = "pallet-chainbridge"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "FRAME example pallet"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
frame-support = { version = "3.0.0", default-features = false, path = "../support" }
frame-system = { version = "3.0.0", default-features = false, path = "../system" }
pallet-balances = { version = "3.0.0", default-features = false, path = "../balances" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../primitives/runtime" }
sp-std = { version = "3.0.0", default-features = false, path = "../../primitives/std" }
sp-io = { version = "3.0.0", default-features = false, path = "../../primitives/io" }
sp-core = { version = "3.0.0", path = "../../primitives/core", default-features = false }

frame-benchmarking = { version = "2.0.0", default-features = false, path = "../benchmarking", optional = true }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-runtime/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"sp-io/std",
<<<<<<< HEAD:frame/chainbridge/Cargo.toml
	"sp-std/std"
=======
	"sp-keystore",
	"sp-runtime/std",
	"sp-std/std",
>>>>>>> 49a4103f4bfef55be20a5c6d26e18ff3003c3353:frame/example-offchain-worker/Cargo.toml
]
runtime-benchmarks = ["frame-benchmarking"]
