name: Build and push image to ECR
on:
  push:
    branches:
      - dev-cere
      - feature/update-proc-macro-2-version
env:
  ECR_REPOSITORY: pos-network-node
jobs:
  build-and-push:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA"
          docker image tag $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  trigger:
    needs: build-and-push
    strategy:
      matrix:
        repo: ['Cerebellum-Network/ddc-e2e-tests']
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cerebellum-Network/ddc-e2e-tests repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: POS_NODE_VERSION_TRIGGER
          client-payload: '{"POS_NODE_VERSION": "${{ github.sha }}"}'
