name: 'Run tests'
on:
  pull_request:
    branches: [dev-cere]
    types: [opened, synchronize, edited]
jobs:
  run-tests:
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: actions/checkout@v2
      - name: 'Checkout submodules'
        run: 'git submodule update --init --recursive'
      - name: 'current disk space'
        run: df -Ph . | tail -1 | awk '{print $4}'
      - name: 'clean up 1'
        run: sudo rm -rf "/usr/local/share/boost"
      - name: 'clean up 2'
        run: sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: 'current disk space 2'
        run: df -Ph . | tail -1 | awk '{print $4}'
      - name: 'Run tests'
        run: |
          docker build . --no-cache -f Dockerfile.tests
      - name: 'current disk space'
        run: df -Ph . | tail -1 | awk '{print $4}'
      - name: 'disks space'
        run: df -h
