name: Run tests
on:
  push:
    branches:
      - feature/eth-chain-bridge
  pull_request:
    branches:
      - dev-cere
    types:
      - opened
      - synchronize
      - edited

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v3
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Free space
        run: df -h
      - name: Run tests
        run: docker build . --no-cache -f Dockerfile.tests
      - name: Free space
        run: df -h
