name: 'Run tests 2'
on:
  pull_request:
    branches: [dev-cere]
    types: [opened, synchronize, edited]
jobs:
  run-tests:
    runs-on: 'ubuntu-18.04'
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - uses: actions/checkout@v2
      - name: 'Checkout submodules'
        run: 'git submodule update --init --recursive'
      - name: 'current disk space'
        run: df -Ph . | tail -1 | awk '{print $4}'
      - name: 'Clean up 1'
        run: sudo rm -rf "/usr/local/share/boost"
      - name: 'Clean up 2'
        run: sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: 'Current disk space'
        run: df -Ph . | tail -1 | awk '{print $4}'
      - name: 'Run tests'
        run: |
          docker build . --no-cache -f Dockerfile.tests-2
      - name: 'Current disk space'
        run: df -Ph . | tail -1 | awk '{print $4}'
      - name: 'Disks space'
        run: df -h
