name: 'Build and push Docker image'
on:
  push:
    branches:
      - 'dev-cere'
      - 'feature/integrate-test-in-ci-flow'
  pull_request:
    branches:
      - 'dev-cere'
env:
  ECR_REPOSITORY: 'crb-substrate-testnet-node'
  IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}
jobs:
  build-and-push:
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v1'
      - name: 'Checkout submodules'
        run: 'git submodule update --init --recursive'
      - name: 'Install Environment'
        run: |
          apt-get update && \
          apt-get upgrade -y && \
          apt-get install -y cmake pkg-config libssl-dev git clang
      - name: 'Install Rust and execute test'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y && \
          export PATH=$PATH:$HOME/.cargo/bin && \
          scripts/init.sh && \
          cargo +nightly-2020-10-06 test
