name: 'Automation test CI flow'
on:
  push:
    branches:
      - 'dev-cere'
      - 'feature/cbi-81-test-in-ci-flow'
env:
  ECR_REPOSITORY: 'crb-substrate-testnet-node'
  IMAGE_TAG: ${{ github.run_number }}-${{ github.sha }}
jobs:
  build-and-push:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev-cere
      - name: 'Checkout submodules'
        run: 'git submodule update --init --recursive'
      - name: 'Install rust environment then test'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build . --no-cache -f Dockerfile.UT